// Synthetic rental portfolio. Real POIs have explicit source references; no real guests.
import { randomBytes } from 'node:crypto';
import { templatePreview } from './assistant-service.mjs';
export function populateDemo(store) {
  const marker='rental-demo-2026-10';
  const add=(collection,row)=>{if(!store[collection].some(x=>x.id===row.id))store[collection].push({...row,demoFixture:marker});};
  const en=(values)=>({en:values});
  const texts=templatePreview({checkoutTime:'11:00',quietFrom:'22:00',quietTo:'08:00'});
  const current=store.apartments.find(a=>a.id==='apartment-demo');
  const elena=store.contacts.find(c=>c.id===current?.managerId);
  if(elena&&!elena.translations)elena.translations=en({name:'Elena',note:'Your personal rental manager. I can help with arrival, apartment questions and your stay.'});
  add('contacts',{id:'demo-manager-maria',name:'Мария',role:'Персональный менеджер по аренде',phone:'',whatsapp:'',photo:'',note:'Помогу организовать заезд, продлить проживание и решить бытовые вопросы. Напишите через форму — обращение сохранится у вашей квартиры.',translations:en({name:'Maria',note:'I can help with check-in, extending your stay and everyday questions. Use the request form so your message stays linked to your apartment.'})});
  add('contacts',{id:'demo-manager-denis',name:'Денис',role:'Персональный менеджер по аренде',phone:'',whatsapp:'',photo:'',note:'На связи по вопросам проживания: Wi-Fi, техника, уборка и выезд. В обращении можно описать вопрос — номер квартиры уже передастся автоматически.',translations:en({name:'Denis',note:'I can help with Wi-Fi, appliances, housekeeping and check-out. Your apartment is added to your request automatically.'})});
  add('contacts',{id:'demo-host-mehmet',name:'Мехмет',role:'Управляющий комплексом',phone:'',whatsapp:'',photo:'',note:'Вопросы общих зон, доступа в здание и инфраструктуры комплекса передавайте через персонального менеджера.',translations:en({name:'Mehmet',note:'Please contact your personal manager about shared areas, building access and residence facilities.'})});
  const facilities='Открытый бассейн: 09:00–20:00.\nФитнес-зал: 08:00–21:00; вход по карте гостя.\nПарковка: свободные места без предварительного бронирования.\nШезлонги и зонты — в зоне бассейна. Полотенца берите из квартиры.\nЭто условия демонстрационного комплекса.';
  const facilitiesEn='Outdoor pool: 09:00–20:00.\nGym: 08:00–21:00; use your guest access card.\nParking: unreserved spaces, subject to availability.\nSun loungers and parasols are in the pool area. Bring towels from your apartment.\nThese are illustrative residence arrangements.';
  for(const [id,name] of [['demo-oba-garden','Oba Garden Residence'],['demo-oba-terrace','Oba Terrace Residence']])add('complexes',{id,name,district:'Оба, Аланья',address:'Oba Mahallesi, Alanya, Antalya, Türkiye · демонстрационный объект',addressTaxi:`Oba Mahallesi, Alanya — ${name}. Örnek tesis; gerçek bina adresi değildir.`,mapUrl:'https://www.google.com/maps/search/?api=1&query=Oba+Alanya',rules:texts.rules,facilities,translations:en({rules:texts.rulesEn,facilities:facilitiesEn}),instructionTemplate:{instructions:texts.instructions,checkout:texts.checkout,translations:en({instructions:texts.instructionsEn,checkout:texts.checkoutEn})}});
  const base=store.complexes.find(c=>c.id==='demo-residence');
  if(base&&!base.demoContentVersion){base.rules=texts.rules;base.facilities=facilities;base.translations=en({rules:texts.rulesEn,facilities:facilitiesEn});base.demoContentVersion=marker;}
  if(current&&!current.demoContentVersion){current.instructions=texts.instructions+'\nТелевизор: выберите источник HDMI 1 для приставки. Не выходите из гостевого профиля.';current.checkout=texts.checkout+'\nОставьте использованные полотенца в ванной, вынесите мусор и сообщите менеджеру, что вы выехали.';current.translations=en({instructions:texts.instructionsEn+'\nTV: select HDMI 1 for the media box. Keep the guest profile signed in.',checkout:texts.checkoutEn+'\nLeave used towels in the bathroom, take out the rubbish and message your manager when you leave.'});current.demoContentVersion=marker;}
  const rows=[['demo-apt-12','Квартира 12 · 1+1','demo-residence',elena?.id],['demo-apt-36','Квартира 36 · 2+1','demo-residence','demo-manager-maria'],['demo-apt-a08','A08 · Студия','demo-oba-garden','demo-manager-denis'],['demo-apt-a21','A21 · 1+1 с балконом','demo-oba-garden','demo-manager-maria'],['demo-apt-b14','B14 · Семейная 2+1','demo-oba-garden',elena?.id],['demo-apt-t05','T05 · 1+1 с террасой','demo-oba-terrace','demo-manager-denis'],['demo-apt-t18','T18 · Пентхаус 2+1','demo-oba-terrace','demo-manager-maria']];
  for(const [id,name,complexId,managerId] of rows)add('apartments',{id,name,complexId,managerId:managerId||'demo-manager-maria',hostId:complexId==='demo-residence'?'host-demo':'demo-host-mehmet',token:randomBytes(18).toString('hex'),wifiName:`Stay_${id.replace('demo-apt-','').toUpperCase()}`,wifiPassword:`Stay${id.slice(-3).replace('-','').toUpperCase()}2026!`,photo:'/assets/apartment.jpg',instructions:texts.instructions,checkout:texts.checkout,translations:en({instructions:texts.instructionsEn,checkout:texts.checkoutEn}),isDemo:true});
  const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
  const poi=(id,name,category,description,descriptionEn,detail,detailEn,mapUrl,sourceUrl,extra={})=>({id,name,category,description,detail,mapUrl,sourceUrl,...extra,translations:en({name,description:descriptionEn,detail:detailEn})});
  const places=[
    poi('migros','Migros · Çarşamba Cd.','shop','Продукты и покупки для квартиры','Groceries and apartment essentials','Çarşamba Cd., Oba, Alanya. Часы работы проверьте в картах перед визитом.','Çarşamba Cd., Oba, Alanya. Check current opening hours in maps before visiting.',map('36.5498536,32.0425487'),'https://www.openstreetmap.org/way/974994876',{source:'OpenStreetMap',sourceId:'way/974994876',latitude:36.5498536,longitude:32.0425487}),
    poi('migros-jet','Migros Jet · 29. Sk.','shop','Небольшой магазин для повседневных покупок','A local store for everyday shopping','29. Sk., Oba, Alanya. Ассортимент и часы уточняйте у магазина.','29. Sk., Oba, Alanya. Check the store for its current range and hours.',map('36.5384297,32.0366854'),'https://www.openstreetmap.org/node/5625554922',{source:'OpenStreetMap',sourceId:'node/5625554922',latitude:36.5384297,longitude:32.0366854}),
    poi('market','Oba Pazartesi Pazarı','market','Районный базар в Оба','Neighbourhood market in Oba','В муниципальном перечне указан понедельник. Перед поездкой проверьте актуальные место и расписание: публикация источника архивная.','The municipal listing names Monday. Confirm the current location and schedule before visiting; the source is an archived announcement.',map('Oba Pazartesi Pazarı Alanya'),'https://www.alanya.bel.tr/Haber/2692/PAZARYERLERI-TEK-TEK-DENETLENDI'),
    poi('pharmacy','Erenleroba Eczanesi','health','Аптека на Çarşamba Cd.','Pharmacy on Çarşamba Cd.','Çarşamba Cd., Oba, Alanya. Часы в источнике не указаны; статус дежурной аптеки не подтверждён.','Çarşamba Cd., Oba, Alanya. Hours are not listed; on-duty status is not confirmed.',map('36.5557419,32.0631205'),'https://www.openstreetmap.org/node/13722595601',{source:'OpenStreetMap',sourceId:'node/13722595601',latitude:36.5557419,longitude:32.0631205}),
    poi('hospital','Alanya Eğitim ve Araştırma Hastanesi','health','Государственная больница в Оба','Public hospital in Oba','Адрес по официальному сайту: Oba Mahallesi, Alkü Hastane Cad. No: 13, Alanya. Уточняйте порядок приёма непосредственно в учреждении.','Official address: Oba Mahallesi, Alkü Hastane Cad. No: 13, Alanya. Contact the hospital about admission arrangements.',map('Alanya Eğitim ve Araştırma Hastanesi'),'https://alanyaeah.saglik.gov.tr/TR%2C13785/bize-ulasin.html'),
    poi('cafe','Solovay Cafe','food','Кафе на Keykubat Bulvarı','Café on Keykubat Bulvarı','Keykubat Bulvarı, Oba, Alanya. Меню, наличие мест и часы работы уточняйте у заведения.','Keykubat Bulvarı, Oba, Alanya. Check directly for menus, availability and hours.',map('36.5405727,32.0316323'),'https://www.openstreetmap.org/node/13572580601',{source:'OpenStreetMap',sourceId:'node/13572580601',latitude:36.5405727,longitude:32.0316323}),
    poi('onebite','OneBite Cafe','food','Кафе на Albeni Sk.','Café on Albeni Sk.','Albeni Sk. 15/B, Oba. Часы работы в источнике не указаны.','Albeni Sk. 15/B, Oba. Opening hours are not listed in the source.',map('36.5446327,32.041329'),'https://www.openstreetmap.org/node/12769981984',{source:'OpenStreetMap',sourceId:'node/12769981984',latitude:36.5446327,longitude:32.041329}),
    poi('coast','Набережная Оба — Тосмур','beach','Прогулка вдоль моря','A walk along the seafront','Прибрежная зона между Оба и Тосмуром. Ссылка открывает поиск района; конкретный вход на пляж и условия доступа проверьте в картах.','Seafront between Oba and Tosmur. The link opens an area search; check maps for a specific beach entrance and access conditions.',map('Oba Tosmur sahil Alanya'),'https://www.alanya.bel.tr/Documents/Faaliyet/2024/2024.pdf')
  ];
  const placeholders=new Set(['shop-demo','market-demo','pharmacy-demo','hospital-demo','beach-demo','cafe-demo']);
  store.places=store.places.filter(p=>!(placeholders.has(p.id)&&['Супермаркет рядом','Местный базар','Аптека','Больница','Пляж','Кафе и рестораны'].includes(p.name)));
  for(const complexId of ['demo-residence','demo-oba-garden','demo-oba-terrace'])for(const p of places)add('places',{...p,id:`fixture-${complexId}-${p.id}`,complexId,retrievedAt:'2026-10-08'});
  const guests=[['Александр К.','apartment-demo','2026-10-05','2026-10-14'],['Марина С.','demo-apt-12','2026-10-07','2026-10-17'],['Семья Волковых','demo-apt-36','2026-10-02','2026-10-12'],['Ольга П.','demo-apt-a08','2026-10-08','2026-10-15'],['Артём и Анна','demo-apt-a21','2026-10-10','2026-10-24'],['Семья Орловых','demo-apt-b14','2026-10-04','2026-10-18'],['Дмитрий М.','demo-apt-t05','2026-10-06','2026-10-20'],['Екатерина Л.','demo-apt-t18','2026-10-09','2026-10-23']];
  guests.forEach(([name,apartmentId,arrival,departure],i)=>{const a=store.apartments.find(a=>a.id===apartmentId);add('stays',{id:`fixture-stay-${i+1}`,name,apartmentId,managerId:a.managerId,arrival,departure,token:randomBytes(18).toString('hex')});});
  const messages=[['service','Не удаётся подключить телевизор к Wi-Fi. Телефон подключается.','new'],['sales','Ищем 1+1 для отдыха семьи. Интересуют квартиры в Оба.','new'],['service','Можно заказать дополнительную уборку на пятницу?','in_progress'],['sales','Рассматриваем 2+1 для переезда. Нужна подборка рядом со школами.','in_progress'],['service','Планируем поздний выезд. Подскажите доступность и стоимость.','new'],['sales','Хотим сравнить варианты для сдачи в аренду.','done'],['service','Спасибо, вопрос с кондиционером решён.','done'],['service','Подскажите порядок передачи ключей при раннем выезде.','in_progress'],['sales','Нужны варианты с террасой. Готовы посмотреть во время отпуска.','new'],['service','Просим второй комплект постельного белья.','done'],['sales','Интересует готовая квартира с мебелью.','in_progress'],['service','Можно ли продлить проживание ещё на три ночи?','new']];
  messages.forEach(([type,message,status],i)=>{const stay=store.stays.find(s=>s.id===`fixture-stay-${i%8+1}`),a=store.apartments.find(a=>a.id===stay.apartmentId),c=store.complexes.find(c=>c.id===a.complexId);add('leads',{id:`fixture-lead-${i+1}`,isDemo:true,type,name:stay.name,contact:`Демо-контакт · ••• ${String(1200+i)}`,goal:type==='sales'?['Для отдыха','Для жизни','Для аренды'][i%3]:'',budget:type==='sales'?['€100 000–200 000','€200 000–350 000','Пока не определился'][i%3]:'',message,status,consent:true,consentVersion:'demo-synthetic-no-real-consent',apartmentId:a.id,stayId:stay.id,guestName:stay.name,apartmentName:a.name,complexName:c.name,district:c.district,managerName:store.contacts.find(x=>x.id===stay.managerId)?.name||'',source:type==='sales'?store.banner.title:'Помощь по проживанию',createdAt:new Date(Date.UTC(2026,9,8,8,30)-i*3*3600000).toISOString(),telegramStatus:'demo',attempts:0});});
  store.leads.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  return store;
}
