export const seed = {
  complexes: [{ id: 'demo-residence', name: 'Mediterranean Residence', district: 'Оба, Аланья', address: 'Oba Mahallesi, Alanya, Antalya, Türkiye', addressTaxi: 'Oba Mahallesi, Alanya. Demo adres — lütfen konumu kontrol edin.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=Oba+Alanya', rules: 'Бассейн: 09:00–20:00.\nПожалуйста, соблюдайте тишину после 22:00.\nНе оставляйте личные вещи в общих зонах.', facilities: 'Бассейн, тренажёрный зал, зона отдыха.\nДемонстрационные данные: уточните условия у управляющего.' }],
  contacts: [{ id: 'host-demo', name: 'Александр', role: 'Управляющий', phone: '', whatsapp: '+905394418740', telegram: '@staypropertyveronika', photo: '/assets/host-demo.jpg', translations: { en: { name: 'Alexander' } }, note: 'Помогу с вопросами по квартире и проживанию.' }, { id: 'rental-demo', name: 'Елена', role: 'Персональный менеджер по аренде', phone: '', whatsapp: '+905394418740', telegram: '@staypropertyveronika', photo: '/assets/manager.jpg', note: 'Я ваш персональный менеджер. Помогу с заселением и вопросами во время отдыха.' }],
  apartments: [{ id: 'apartment-demo', token: 'demo', name: 'Квартира 24', complexId: 'demo-residence', managerId: 'rental-demo', hostId: 'host-demo', wifiName: 'Stay_Guest', wifiPassword: 'Welcome2026', photo: '/assets/apartment.jpg', checkout: 'Выезд до 11:00.\nПожалуйста, выключите кондиционер, закройте окна и сообщите управляющему о выезде.\nПередачу ключей согласуйте заранее.', instructions: 'Кондиционер: закройте окна перед включением, используйте режим охлаждения.\nСтиральная машина: выбирайте программу по типу ткани, не перегружайте барабан.\nПри неполадках напишите управляющему.', isDemo: true }],
  places: [
    { id: 'shop-demo', complexId: 'demo-residence', category: 'shop', name: 'Супермаркет рядом', description: 'Продукты и всё необходимое для отдыха', detail: 'Добавьте проверенный магазин и часы работы в админке.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=supermarket+Oba+Alanya' },
    { id: 'market-demo', complexId: 'demo-residence', category: 'market', name: 'Местный базар', description: 'Овощи, фрукты и местные продукты', detail: 'Дни и часы работы уточняйте у управляющего.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=market+Oba+Alanya' },
    { id: 'pharmacy-demo', complexId: 'demo-residence', category: 'health', name: 'Аптека', description: 'Найти аптеку в районе', detail: 'Дежурную аптеку уточняйте у управляющего. Точки на карте — результаты поиска.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=eczane+Oba+Alanya' },
    { id: 'hospital-demo', complexId: 'demo-residence', category: 'health', name: 'Больница', description: 'Медицинская помощь рядом', detail: 'В экстренной ситуации используйте экстренную службу, а не форму сайта.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=hospital+Alanya' },
    { id: 'beach-demo', complexId: 'demo-residence', category: 'beach', name: 'Пляж', description: 'Море, прогулки и вечерние закаты', detail: 'Демонстрационная подборка мест. Проверьте маршрут перед выходом.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=beach+Oba+Alanya' },
    { id: 'cafe-demo', complexId: 'demo-residence', category: 'food', name: 'Кафе и рестораны', description: 'Завтрак или ужин в вашем районе', detail: 'В полной версии здесь будет подборка команды Stay Property.', mapUrl: 'https://www.google.com/maps/search/?api=1&query=restaurants+Oba+Alanya' }
  ],
  banner: { title: 'Нравится этот район?', text: 'Подберём 3 квартиры для покупки под ваш бюджет.', button: 'Получить подборку', photo: '/assets/residence.jpg', enabled: true },
  stays: [],
  leads: []
};
